# Generated by Django 4.1.7 on 2023-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tech",
            name="status",
            field=models.CharField(
                choices=[
                    ("Iniciante", "Beginner"),
                    ("Intermediário", "Intermediate"),
                    ("Avançado", "Advanced"),
                ],
                default="Iniciante",
                max_length=256,
            ),
        ),
    ]
