# Generated by Django 4.1.7 on 2023-03-30 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("techs", "0003_tech_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tech",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="techs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
