# Generated by Django 4.1.7 on 2023-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_url_user_bio_user_course_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default='A cool bio', max_length=256),
            preserve_default=False,
        ),
    ]
