# Generated by Django 4.1.7 on 2023-03-30 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
